### ISSUE TITLE
MySQl.pl is hard coded for port 3306  this causes problems when that is not the MYSQL port 

### ISSUE THREAD

**Issue by mxdog** [ProjectEQ/projecteqquests#1345]
I am not comfortable proposing commits yet  but propose this one if any one cares to look 
 I had troubles with this and just saw someone on discus with the same problem with updates on NOT 3306 

PLUGINS : FILE : MySQL.pl 
line 25 
add /insert :  $port = $config->{"server"}{"database"}{"port"};

line 31 
change :  $dsn = "dbi:mysql:$db:$host:3306";
to :          $dsn = "dbi:mysql:$db:$host:$port";

then ( and i have not looked at it yet  ) the install script  install.sh and/or eqemu_server.pl should prompt for a port on first run if eqemu_config.json does not exist or the port is not defined in the config file and default to 3306 if non entered.

EXAMPLE eqemu_config.json section :

  "database": {
   "db": "eqworld1",
   "host": "127.0.0.1",
   "password": "SUPE-SECRET",
   "port": "3853",                   *********  NOT 3306 *********
   "username": "EqDbAdmin"

**Comment by fryguy503** [comment]
Updated script, thank you for the report.
