### ISSUE TITLE
non-existant callback War_Combat, Weaponry_Death and more

### ISSUE THREAD

**Issue by xackery** [ProjectEQ/projecteqquests#1362]
https://github.com/ProjectEQ/projecteqquests/blob/396f0f615e8a318d2009fac004a87e07ce33121a/bloodfields/encounters/war.lua#L55

Function above calls a commented out function War_Combat

**Comment by xackery** [comment]
Another: 
https://github.com/ProjectEQ/projecteqquests/blob/396f0f615e8a318d2009fac004a87e07ce33121a/chambersb/encounters/mpg_weaponry.lua#L161

**Comment by joligario** [comment]
Will defer to @huffin. He may have wanted to disable calling that function.

**Comment by xackery** [comment]
Some more:

- [ ] https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/codecay/encounters/Carp.lua#L155
- [ ] https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/codecay/encounters/Carp.lua#L172
- [ ] https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/codecay/encounters/Carp.lua#L175
- [ ] https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/dranik/encounters/battlemaster.lua#L158
- [ ] https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/hohonora/encounters/maidens.lua#L186 (there is additionally bad refs to at lines 188, 190, 192 to SpawnTimer
- [ ] https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/misty/encounters/Misty.lua#L754 and 755
- [ ] https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/tacvi/encounters/pkk.lua#L246
- [ ] https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/tacvi/encounters/zmkp.lua#L312
- [ ] https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/takc/encounters/takc.lua#L283
- [ ] https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/txevu/encounters/champ.lua#L353
- [ ]

**Comment by fryguy503** [comment]
Addressed all concerns.
