### ISSUE TITLE
Hierophant_Oxyn has a 3rd arg to check_turn_in

### ISSUE THREAD

**Issue by xackery** [ProjectEQ/projecteqquests#1366]
This function expects a maximum of 2 argument(s) but instead it is receiving 3.

https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/cabeast/Hierophant_Oxyn.lua#L37

https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/cabeast/Hierophant_Oxyn.lua#L42

https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/cabeast/Hierophant_Oxyn.lua#L48

**Comment by xackery** [comment]
https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/crystal/a_geonid.lua#L5
https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/crystal/Historian_Baenek.lua#L35
https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/fieldofbone/Oracle_Vauris.lua#L21
https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/jaggedpine/#Guard_Finewine.lua#L23
https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/jaggedpine/#Guard_Finewine.lua#L25
https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/jaggedpine/#Guard_Finewine.lua#L25
https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/jaggedpine/#Guard_Finewine.lua#L28
https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/jaggedpine/#Sergeant_Caelin.lua#L31
https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/jaggedpine/#Sergeant_Caelin.lua#L36
https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/jaggedpine/#Sergeant_Caelin.lua#L39
https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/katta/#Condor.lua#L16
https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/katta/Legionnaire_Claudius.lua#L11
https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/necropolis/#a_ghostly_presence.lua#L9
https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/necropolis/#Spirit_of_Garzicor_.lua#L9
https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/necropolis/#Spirit_of_Garzicor.lua#L9
https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/qcat/an_investigator.lua#L14
https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/qcat/Guard_Helminth.lua#L20
https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/qeynos/Runethar_Hamest.lua#L43
https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/qeynos/Runethar_Hamest.lua#L50
https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/qeynos2/Priestess_Jahnda.lua#L38
https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/qeynos2/Vegalys_Keldrane.lua#L65
https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/qeytoqrg/Niclaus_Ressinn.lua#L19
https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/qeytoqrg/Niclaus_Ressinn.lua#L22
https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/skyshrine/#Eldriaks_Fe-Dhar.lua#L36
https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/skyshrine/#Eldriaks_Fe-Dhar.lua#L42
https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/skyshrine/#Eldriaks_Fe-Dhar.lua#L48
https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/skyshrine/#Eldriaks_Fe-Dhar.lua#L51
https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/skyshrine/#Eldriaks_Fe-Dhar.lua#L54
https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/skyshrine/#Oglard.lua#L34
https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/skyshrine/#Oglard.lua#L40
https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/skyshrine/Oglard.lua#L34
https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/skyshrine/Oglard.lua#L40
https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/thurgadina/#Loremaster_Sarl_.lua#L11

**Comment by joligario** [comment]
I guess I should have scrolled down...
