### ISSUE TITLE
arg count invalid on a_Thul_Tae_Ew_High_Priest  and other NPCs

### ISSUE THREAD

**Issue by xackery** [ProjectEQ/projecteqquests#1367]
This function expects a maximum of 0 argument(s) but instead it is receiving 1.

https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/cazicthule/#a_Thul_Tae_Ew_High_Priest.lua#L28

So, this is more just an ordering warning, it seems:
<img width="303" alt="Screen Shot 2023-01-21 at 9 03 50 AM" src="https://user-images.githubusercontent.com/845670/213878263-5adc3e45-e9cb-4743-8b5e-ca1c4819eb28.png">

my linter is thinking another file in the same path is taking priority on spawn_guard() <-- with no args, because spawn_guards(e) defined in this file is declared AFTER the function call.

I don't think quest api works this way, but figured i'd share the warning anyways.

This is remedied by shifting up the spawn_guards(e) function up a bit.

**Comment by xackery** [comment]
Another of a similar situation:
https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/chambersd/encounters/mpg_specialization.lua#L84

**Comment by fryguy503** [comment]
Issues addressed
