### ISSUE TITLE
undefined globals 

### ISSUE THREAD

**Issue by xackery** [ProjectEQ/projecteqquests#1368]
- [x] https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/inktuta/encounters/noqufiel.lua#L156 Undefined global `max_hp`.
- [x] https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/lavastorm/a_fire_goblin_scout.lua#L4 Undefined global `scorchfist`.
- [x] https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/misty/encounters/Misty.lua#L501 Undefined global `deputyold_min_hit`.
- [x] https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/misty/encounters/Misty.lua#L502 Undefined global `deputyold_max_hit`.
- [x] https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/misty/encounters/Misty.lua#L522 Undefined global `deputyold_min_hit`.
- [x] https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/misty/encounters/Misty.lua#L523 Undefined global `deputyold_max_hit`.
- [x] https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/poknowledge/Borik_Darkanvil.lua#L26 Undefined global `platinum`. (should be e.platinum)
- [x] https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/potimeb/zone_status.lua#L661 Undefined global `expedition`. This one seems to be due to the fact that expedition is local scoped in event_spawn yet gets ref'd in event_timer.
- [x] https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/qeynos2/Astaed_Wemor.lua#L33 Undefined global `ChooseRandom`.
- [x] https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/qeynos2/Flynn_Merrington.lua#L10 Undefined global `tax`.
- [x] https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/qeytoqrg/Baobob_Miller.lua#L43 Undefined global `gold`.
- [x] https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/qeytoqrg/Baobob_Miller.lua#L53 Undefined global `gold`.
- [x] https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/qeytoqrg/Baobob_Miller.lua#L63 Undefined global `gold`.
- [x] https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/qeytoqrg/Chanda_Miller.lua#L44 Undefined global `gold`.
- [x] https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/qeytoqrg/Chanda_Miller.lua#L54 Undefined global `gold`.
- [x] https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/qeytoqrg/Chanda_Miller.lua#L64 Undefined global `gold`.
- [x] https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/qeytoqrg/Mira_Sayer.lua#L9 Undefined global `tax`.
- [x] https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/rivervale/Blinza_Toepopal.lua#L7 Undefined global `timer`. Undefined global `jillin`.
- [x] https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/rivervale/Daleen_Leafsway.lua#L18 Undefined global `timer`. Undefined global `blurt`.
- [x] https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/rivervale/Fiddy_Bobick.lua#L9 Undefined global `wp`.
- [x] https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/rivervale/Gaffin_Deeppockets.lua#L6 Undefined global `timer`. Undefined global `lenny`.
- [x] https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/freporte/Brunar_Rankin.lua#L18 Undefined global `item_lib`.
- [x] https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/poknowledge/Vivian_the_True.lua#L26 Undefined global `item_lib`.
- [x] https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/tutorialb/Frizznik_Hailstorm.lua#L35 Undefined global `item_lib`.

**Comment by xackery** [comment]
This one I think is a false positive, but it's strange..
https://github.com/ProjectEQ/projecteqquests/blob/f678149a12f6b6efbe3c44cbfe06e68c01b3fbfc/everfrost/Rombus.lua#L56 Undefined global `item_lib`.

Yet.. the required is declared. In other files, when local item_lib = require("items") is declared, the item_lib refs are identified and resolved, but just this one seems to have this case.. Dunno.
<img width="447" alt="Screen Shot 2023-01-21 at 9 23 33 AM" src="https://user-images.githubusercontent.com/845670/213879173-319c3511-49de-477b-a425-af4b26f70928.png">

**Comment by fryguy503** [comment]
copper, silver, gold, platinum do not need to be e.copper, e.silver, e.gold, e.platinum as they are part of e.trade and it is handled in the item_lib script

**Comment by fryguy503** [comment]
All issues addressed
