### ISSUE TITLE
Lua math.random values need check

### ISSUE THREAD

**Issue by joligario** [ProjectEQ/projecteqquests#1379]
https://github.com/ProjectEQ/projecteqquests/blob/9302f35f04c386df998e1f58f0d89a71411cf93a/lua_modules/npc_ext.lua#L46

This call needs to be re-evaluated. In `math.random(a, b)`, Lua will select a number from a up to b. If b is empty or lower than a, it will throw an error such as:
`quests/lua_modules/npc_ext.lua:46: bad argument #2 to 'random' (interval is empty)` from the logs on Discord

cc: @fryguy503

**Comment by fryguy503** [comment]
Thanks, I will take a look at the overall logic when I get a moment and re-write it. Looks like this was written to try and mirror step for step the perl version.

**Comment by fryguy503** [comment]
Cleaned up the logic and added a quick flip for negative secondary roll arguments.

https://github.com/ProjectEQ/projecteqquests/commit/7e7d683
