### ISSUE TITLE
PoJ "other" Reference Error

### ISSUE THREAD

**Issue by joligario** [ProjectEQ/projecteqquests#1387]
https://github.com/ProjectEQ/projecteqquests/blob/f093c3282b47bdac7347cac9cfc5d8666380aae7/pojustice/201438.lua#L87

`quests/pojustice/201438.lua:87: attempt to index field 'other' (a nil value)`

**Comment by fryguy503** [comment]
https://github.com/ProjectEQ/projecteqquests/commit/07cb37c
