### ISSUE TITLE
Patch for /trunk/quests/warslikswood/Crusader_Eaxl.pl

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ProjectEQ/projecteqquests#3]
```
added to to the line to make sense
```

Original issue reported on code.google.com by `ahad...@madison-academy.org` on 30 Dec 2011 at 11:54

Attachments:
* [Crusader_Eaxl.pl.patch](https://storage.googleapis.com/google-code-attachments/projecteqquests/issue-1/comment-0/Crusader_Eaxl.pl.patch)

**Comment by joligario** [comment]
Already fixed with #1 and #2. Database driven emotes replaced these scripts after that.
