### ISSUE TITLE
Felwithea - Terran_Starwatcher can't ask about weapon quest

### ISSUE THREAD

**Issue by Trystanosaurus** [ProjectEQ/projecteqquests#715]
Currently you can't ask Terran Starwatcher in Felwithe about the cleric newbie weapon quest.

The chat link to ask about it is [further guidance] which is currently further down the else if chain than just [guidance] (which is his general intro) in his lua file. 

The further guidance bit needs to be moved to the top of the file or you end up only getting his intro.

**Comment by joligario** [comment]
Thanks!
