### ISSUE TITLE
Felwitheb - Yuin Starchaser: Art keepers task text

### ISSUE THREAD

**Issue by Trystanosaurus** [ProjectEQ/projecteqquests#716]
Currently when you hand in the Orc Thaumaturgists Spell Book to Yuin Starchser for the newbie caster staff quest there's a made up text:
`e.self:Say("Excellent work, " .. e.other:GetName() .. ". Now I need you to gather a Pristine Forest Drakeling Scale and an Arborean Amber. Return this staff and the items I require and then I will create your new staff."); -- Text made up`

According to Allakhazam (http://everquest.allakhazam.com/db/quest.html?quest=2043) the text should be..
`e.self:Say("Well done young Art Keeper. Take this Rough Art Keepers Initiate Staff and go forth and gather a Pristine Forest Drakeling Scales and an Arborean Amber. When you have acquired those two items return them to me with the Rough Art Keepers Initiate Staff and I will put the final touches on the staff."); `

**Comment by joligario** [comment]
Thanks!
